### PR TITLE
Fix: Remove some bugs from chat context

### PR DESCRIPTION
**Pull request by vcwild**
## Description

- remove bug for chat gateway
- fix bug where user was able to find promote to admin button

### CODE REVIEW

**Comment by iaurg** [comment]
LGTM 🧨

**Comment by vcwild** [comment]
pls review @iaurg @julianochoi @GuiMartinelli

**Review by iaurg — APPROVED** [review]

**Comment by vcwild** [comment]
@iaurg can you please handle the merge conflicts? I don't know what is changed in the main.

**Comment by iaurg** [comment]
> @iaurg can you please handle the merge conflicts? I don't know what is changed in the main.

Solved. In the main, I've changed the 'myUser' list to an object, so that we don't need to iterate.

**Comment by vcwild** [comment]
> > @iaurg can you please handle the merge conflicts? I don't know what is changed in the main.
> 
> Solved. In the main, I've changed the 'myUser' list to an object, so that we don't need to iterate.

thank you

**Pull request merged**
